name: Build and Test

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake
      
      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
      - name: Build C++ core (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          cd build
          cmake -DBUILD_PYSOLNP=FALSE -DRUN_CODECOV=FALSE ..
          cmake --build . --config Release
      
      - name: Build C++ core (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake -DBUILD_PYSOLNP=FALSE -DRUN_CODECOV=FALSE ..
          cmake --build . --config Release
      
      - name: Build Python bindings (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build_py
          cd build_py
          cmake -DBUILD_PYSOLNP=TRUE -DPYTHON_EXECUTABLE=$(which python) ..
          cmake --build . --config Release
      
      - name: Build Python bindings (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build_py
          cd build_py
          cmake -DBUILD_PYSOLNP=TRUE -DPYTHON_EXECUTABLE=python ..
          cmake --build . --config Release
