name: Run C++ Codecov

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  run_codecov:
    name: Run Codecov using CMake
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake lcov gfortran

      - name: Run CMake with Codecov settings
        run: |
          mkdir build
          cd build
          cmake -DRUN_CODECOV=TRUE ..
          make solnp_tests
          ./solnp_tests -r junit > solnp_tests_result.xml
          make utils_tests
          ./utils_tests -r junit > utils_tests_result.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./build/solnp_tests_result.xml,./build/utils_tests_result.xml
          token: ${{ secrets.CODECOV_TOKEN }}
